inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 100
  Exclude:
    # TODO: Fix that
    - app/controllers/translations_controller.rb

Style/SingleSpaceBeforeFirstArg:
  Enabled: false
