development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wdwBackend_development
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wdwBackend_test
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wdwBackend
  pool: 5
  socket: /var/lib/mysql/mysql.sock
