development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: wdwBackend_development
  pool: 5
  socket: /tmp/mysql.sock
test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: wdwBackend_test
  pool: 5
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: wdwBackend
  pool: 5
  socket: /tmp/mysql.sock

#  development:
#  adapter: mysql2
#  encoding: utf8
#  collation: utf8_general_ci
#  reconnect: false
#  database: fifapredictor
#  pool: 5
#  username: neopoly
#  password: neopoly
#  socket: /var/run/mysqld/mysqld.sock